[connections.postgresql]
url ="postgresql://neondb_owner:lng5dVwjm3hf@ep-billowing-mud-a57hfg39.us-east-2.aws.neon.tech/neondb?sslmode=require"
host="ep-billowing-mud-a57hfg39.us-east-2.aws.neon.tech"
database="neondb"
username="neondb_owner"
password="lng5dVwjm3hf"
port=5432